### ISSUE TITLE
print and printn add '0' in the end of line

### ISSUE THREAD

**Issue by eamanu** [keith-packard/newt#4]
Hello,

When I use the built-in functions print and printn this add a '0' on the end of the line:

![image](https://user-images.githubusercontent.com/7605307/50093937-b9a6b580-01f0-11e9-8cb1-9b0efe96650e.png)

**Comment by eamanu** [comment]
`newt_builtin_print*` is returned NEWT_ZERO. Why? if it is just a print why return? I propose use a "wrapper" that call to existing `newt_built_print*` instructions but returning void

**Comment by eamanu** [comment]
Great! Could I take this enhancement, please?

**Comment by keith-packard** [comment]
Sorry, missed your comment from last month! Of course, if you want to add a 'void' value to avoid printing spurious zeros, that would be fun to see.
